# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PrimeDrive' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PrimeDrive
  pod 'Firebase'
  target 'PrimeDrive-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PrimeDriveTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PrimeDrive-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PrimeDrive-tvOS
end
